import {calculate,periods,dayKey} from './ledger.js';
const $=s=>document.getElementById(s),money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'USD'}).format(n),eth=n=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:8}).format(n),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let trades=[],config={},filter='open',view='overview',busy=false,quote=0;
try{trades=JSON.parse(localStorage.getItem('eth.trades')||'[]');calculate(trades);config=JSON.parse(localStorage.getItem('eth.config')||'{}');quote=Number(localStorage.getItem('eth.quote')||0);}catch(e){alert('Não foi possível carregar os dados locais. Preserve o armazenamento do navegador para recuperar seu backup. '+e.message);throw e;}
let confirmed=new Set(JSON.parse(localStorage.getItem('eth.confirmed')||'[]'));
const notify=s=>{$('toast').textContent=s;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',4500);};
function persist(next){localStorage.setItem('eth.trades',JSON.stringify(next));trades=next;}
function render(){const r=calculate(trades,quote),p=periods(r.sales);$('profits').innerHTML=[['total','Lucro total','Desde a primeira venda'],['day','Lucro diário','Hoje'],['week','Lucro semanal','Segunda a domingo'],['month','Lucro mensal','Mês atual'],['year','Lucro anual','Ano atual']].map(([k,label,desc])=>`<div class="metric"><span>${label}</span><strong class="${p[k]<0?'negative':'positive'}">${money(p[k])}</strong><small>${desc}</small></div>`).join('');$('balance').innerHTML=eth(r.qty)+' <small>ETH</small>';$('capital').textContent=money(r.cost);$('average').textContent=r.qty?money(r.average):'—';$('unrealized').textContent=r.unrealized===null?'—':money(r.unrealized);$('unrealized').className=r.unrealized<0?'negative':'positive';$('fees').textContent=money(r.fees);$('count').textContent=trades.length;$('winRate').textContent=r.sales.length?Math.round(100*r.sales.filter(s=>s.profit>0).length/r.sales.length)+'%':'—';
 const pending=trades.filter(t=>!confirmed.has(t.id)).length;$('syncState').textContent=config.endpoint?`◉ ${pending?pending+' operação(ões) pendente(s) de sincronização':'Google Sheets · última sincronização '+(config.lastSync||'ainda não realizada')}`:'◉ Armazenamento local · Google Sheets não conectado';
 $('tableTitle').textContent=view==='history'?'Histórico de operações':'Compras & posições';$('tableDescription').textContent=view==='history'?'Execuções registradas, com taxas e resultado por venda.':'Cada compra é um lote. Realize vendas totais ou parciais.';document.querySelector('.tabs').hidden=view==='history';
 const search=$('search').value.toLowerCase();let rows=(view==='history'?[...trades].reverse():r.lots.filter(l=>filter==='all'||(filter==='open'?l.remaining>1e-10:l.remaining<=1e-10)).reverse()).filter(t=>(t.id+' '+t.note).toLowerCase().includes(search));
 $('thead').innerHTML=view==='history'?'<tr><th>Operação / data</th><th>Quantidade</th><th>Preço USD</th><th>Taxa efetiva</th><th>Lucro realizado</th><th>Sincronização</th></tr>':'<tr><th>Compra / data</th><th>Saldo ETH</th><th>Custo médio USD</th><th>Capital aberto</th><th>Lucro realizado</th><th>Ação</th></tr>';
 $('tbody').innerHTML=rows.map(t=>{const date=new Date(t.date).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'}),sale=r.sales.find(s=>s.id===t.id);return view==='history'?`<tr><td>${t.type==='buy'?'↙ Compra':'↗ Venda'}<small>${date}</small><small>${esc(t.note)}</small></td><td>${eth(t.qty)} ETH</td><td>${money(t.price)}</td><td>${eth(t.fee)} ${t.feeAsset}</td><td class="${sale?.profit<0?'negative':'positive'}">${sale?money(sale.profit):'—'}</td><td>${confirmed.has(t.id)?'Na planilha':'Local'}</td></tr>`:`<tr><td>Ξ ${esc(t.id.slice(0,8))}<small>${date}</small><small>${esc(t.note)}</small></td><td>${eth(t.remaining)}<small>de ${eth(t.netQty)} ETH</small></td><td>${money(t.unitCost)}</td><td>${money(t.remaining*t.unitCost)}</td><td class="${t.realized<0?'negative':'positive'}">${money(t.realized)}</td><td>${t.remaining>1e-10?`<button data-sell="${esc(t.id)}">Registrar venda ↗</button>`:'Encerrada'}</td></tr>`;}).join('');$('empty').hidden=rows.length>0;$('empty').querySelector('h3').textContent=trades.length?'Nenhuma operação nesta visualização':'Espaço para sua primeira compra';$('empty').querySelector('p').hidden=trades.length>0;$('tableFooter').textContent=rows.length+' registro(s) exibido(s) · Valores líquidos de taxas';
 const daily=new Map();for(const s of r.sales){const key=dayKey(s.date);daily.set(key,(daily.get(key)||0)+s.profit);}let acc=0;const points=[0,...[...daily].sort().map(([,v])=>acc+=v)];if(points.length===1){$('chart').textContent='O gráfico aparece quando você registrar sua primeira venda.';}else {const min=Math.min(...points),max=Math.max(...points),span=max-min||1;const xy=points.map((v,i)=>`${10+i*980/(points.length-1)},${130-(v-min)/span*110}`);$('chart').innerHTML=`<svg viewBox="0 0 1000 155" role="img" aria-label="Lucro acumulado: ${esc(money(acc))}"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#9ecb8a" stop-opacity=".3"/><stop offset="1" stop-color="#9ecb8a" stop-opacity="0"/></linearGradient></defs><path d="M${xy.join(' L')} L990,145 L10,145 Z" fill="url(#area)"/><polyline points="${xy.join(' ')}" fill="none" stroke="#699752" stroke-width="2.5"/><text x="10" y="154" font-size="10" fill="#879180">Primeira venda</text><text x="990" y="154" text-anchor="end" font-size="10" fill="#879180">${esc(money(acc))}</text></svg>`;}}
function openTrade(lot){$('tradeForm').reset();$('type').value=lot?'sell':'buy';$('rate').value=config.defaultRate??0.1;const date=new Date();date.setMinutes(date.getMinutes()-date.getTimezoneOffset());$('date').value=date.toISOString().slice(0,16);$('formError').textContent='';$('lotId').innerHTML=calculate(trades).lots.filter(l=>l.remaining>1e-10).map(l=>`<option value="${l.id}">${l.id.slice(0,8)} · ${eth(l.remaining)} ETH · ${money(l.unitCost)}</option>`).join('');if(lot){$('lotId').value=lot;const l=calculate(trades).lots.find(l=>l.id===lot);$('qty').value=l.remaining;}updateForm();$('tradeDialog').showModal();}
function updateForm(recalc=true){$('lotLabel').hidden=$('type').value!=='sell';$('bnbLabel').hidden=$('feeAsset').value!=='BNB';$('bnbPrice').required=$('feeAsset').value==='BNB';$('feeCurrency').textContent=$('feeAsset').value;const q=+$('qty').value,p=+$('price').value,rate=+$('rate').value/100,b=+$('bnbPrice').value;if(recalc)$('fee').value=Number((q*rate*($('feeAsset').value==='ETH'?1:$('feeAsset').value==='BNB'?(b?p/b:0):p)).toFixed(10));$('tradePreview').textContent=q&&p?`Valor bruto: ${money(q*p)} · Taxa: ${eth(+$('fee').value)} ${$('feeAsset').value}`:'Preencha quantidade e preço para ver o resumo.';}
['type','qty','price','rate','feeAsset','bnbPrice'].forEach(id=>$(id).addEventListener('input',()=>updateForm()));$('fee').addEventListener('input',()=>updateForm(false));
['newTrade','firstBuy'].forEach(id=>$(id).onclick=()=>openTrade());document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('tbody').onclick=e=>{const b=e.target.closest('[data-sell]');if(b)openTrade(b.dataset.sell);};
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('selected',x===b));render();});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));render();if(view==='history')$('tableTitle').scrollIntoView({behavior:'smooth'});});$('search').oninput=render;
 $('tradeForm').onsubmit=async e=>{e.preventDefault();try{const t={id:crypto.randomUUID(),type:$('type').value,date:new Date($('date').value).toISOString(),qty:+$('qty').value,price:+$('price').value,fee:+$('fee').value,feeAsset:$('feeAsset').value,bnbPrice:+$('bnbPrice').value,lotId:$('type').value==='sell'?$('lotId').value:'',note:$('note').value};if(Date.parse(t.date)>Date.now()+60000)throw Error('Use a data de uma execução já realizada.');calculate([...trades,t]);persist([...trades,t]);$('tradeDialog').close();render();notify('Operação salva neste navegador.');if(config.endpoint)await sync();}catch(err){$('formError').textContent=err.message;}};
async function request(action,items=[]){const response=await fetch(config.endpoint,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token:config.token,trades:items}),redirect:'follow',signal:AbortSignal.timeout(25000)});if(!response.ok)throw Error('Google respondeu com erro '+response.status);let result;try{result=await response.json();}catch{throw Error('Resposta inválida. Confira a implantação e a permissão do Apps Script.');}if(!result.ok)throw Error(result.error||'Falha na sincronização');return result;}
async function sync(){if(busy)return;if(!config.endpoint){openSettings();return;}busy=true;$('sync').disabled=true;$('syncState').textContent='↻ Sincronizando com Google Sheets…';try{const remote=await request('read');calculate(remote.trades);const map=new Map(remote.trades.map(t=>[t.id,t]));for(const t of trades){if(map.has(t.id)&&JSON.stringify(map.get(t.id))!==JSON.stringify(t)){const a=map.get(t.id);if(['type','date','qty','price','fee','feeAsset','bnbPrice','lotId','note'].some(k=>a[k]!==t[k]))throw Error('Conflito no registro '+t.id+'. Exporte o backup antes de reconciliar.');}if(!map.has(t.id))map.set(t.id,t);}calculate([...map.values()]);const pending=trades.filter(t=>!remote.trades.some(r=>r.id===t.id));const result=pending.length?await request('append',pending):remote;calculate(result.trades);const merged=new Map(result.trades.map(t=>[t.id,t]));for(const t of trades)if(!merged.has(t.id))merged.set(t.id,t);persist([...merged.values()]);confirmed=new Set(result.trades.map(t=>t.id));localStorage.setItem('eth.confirmed',JSON.stringify([...confirmed]));config.lastSync=new Date().toLocaleString('pt-BR');localStorage.setItem('eth.config',JSON.stringify(config));notify('Sincronização confirmada com a planilha.');}catch(err){notify('Dados locais preservados. '+err.message);$('settingsError').textContent=err.message;}finally{busy=false;$('sync').disabled=false;render();}}
function openSettings(){$('endpoint').value=config.endpoint||'';$('token').value=config.token||'';$('defaultRate').value=config.defaultRate??.1;$('settingsError').textContent='';$('settingsDialog').showModal();}$('settings').onclick=openSettings;$('sync').onclick=sync;
$('settingsForm').onsubmit=async e=>{e.preventDefault();const endpoint=$('endpoint').value.trim();if(endpoint&&!/^https:\/\/script\.google\.com\/macros\/s\/[\w-]+\/exec$/.test(endpoint)){$('settingsError').textContent='Use a URL oficial de implantação do Apps Script terminada em /exec.';return;}if(endpoint&&!$('token').value.trim()){$('settingsError').textContent='Informe a chave de acesso.';return;}const changed=endpoint!==config.endpoint;config={...config,endpoint,token:$('token').value.trim(),defaultRate:+$('defaultRate').value};try{localStorage.setItem('eth.config',JSON.stringify(config));if(changed){confirmed=new Set();localStorage.setItem('eth.confirmed','[]');}render();if(endpoint)await sync();else notify('Configurações salvas.');}catch(err){$('settingsError').textContent=err.message;}};
$('quote').value=quote||'';$('quote').onchange=()=>{quote=+$('quote').value||0;localStorage.setItem('eth.quote',String(quote));$('quoteTime').textContent='Referência manual · '+new Date().toLocaleString('pt-BR');render();};$('getQuote').onclick=async()=>{$('getQuote').disabled=true;try{const response=await fetch('https://api.coinbase.com/v2/prices/ETH-USD/spot',{signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error();const json=await response.json();const price=Number(json.data.amount);if(!(price>0)||json.data.currency!=='USD')throw Error();quote=price;$('quote').value=quote;localStorage.setItem('eth.quote',quote);$('quoteTime').textContent='Coinbase ETH/USD · '+new Date().toLocaleString('pt-BR');render();}catch{notify('Cotação indisponível. Informe o valor manualmente.');}finally{$('getQuote').disabled=false;}};
function download(name,content,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}$('backup').onclick=()=>download('eth-backup-'+dayKey(new Date())+'.json',JSON.stringify({version:1,trades},null,2),'application/json');$('restore').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(data.version!==1||!Array.isArray(data.trades))throw Error('Formato de backup inválido.');const map=new Map(trades.map(t=>[t.id,t]));for(const t of data.trades){if(map.has(t.id)&&JSON.stringify(map.get(t.id))!==JSON.stringify(t))throw Error('Backup contém conflito de ID.');map.set(t.id,t);}calculate([...map.values()]);persist([...map.values()]);render();notify('Backup incorporado sem apagar operações existentes.');}catch(err){notify(err.message);}e.target.value='';};
$('export').onclick=()=>{const sales=calculate(trades).sales,headers=['ID','Tipo','Data UTC','Quantidade ETH','Preço USD','Taxa','Moeda taxa','BNB USD','Compra origem','Nota','Lucro USD'];const csv=[headers,...trades.map(t=>[t.id,t.type,t.date,t.qty,t.price,t.fee,t.feeAsset,t.bnbPrice,t.lotId,t.note,sales.find(s=>s.id===t.id)?.profit??''])].map(row=>row.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(';')).join('\r\n');download('eth-operacoes.csv','\ufeff'+csv,'text/csv;charset=utf-8');};render();
