import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
function backend(){const tables=new Map(),props=new Map(),lock={held:false,waitLock(){this.held=true;},hasLock(){return this.held;},releaseLock(){this.held=false;}};
 function sheet(){const rows=[];const s={rows,getLastRow:()=>rows.length,getMaxRows:()=>1000,insertRowsAfter(){},appendRow:r=>rows.push(r),setFrozenRows(){},setColumnWidth(){},setColumnWidths(){},getRange:(row,col,n,m)=>{if(typeof row==='string')return fmt;return {...fmt,getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>rows[row+i-1]?.[col+j-1]??'')),setValues(values){values.forEach((r,i)=>{rows[row+i-1]??=[];r.forEach((v,j)=>rows[row+i-1][col+j-1]=typeof v==='string'&&v.startsWith("'")?v.slice(1):v);});return this;}};}};const fmt={setFontWeight(){return this;},setBackground(){return this;},setNumberFormat(){return this;},createFilter(){return this;}};return s;}
 const ss={getSheetByName:n=>tables.get(n),insertSheet:n=>{const s=sheet();tables.set(n,s);return s;}};
 const ctx={Intl,Date,Map,Set,JSON,Number,String,Math,Error,PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k),setProperty:(k,v)=>props.set(k,v)})},Utilities:{getUuid:()=>crypto.randomUUID()},SpreadsheetApp:{getActiveSpreadsheet:()=>ss,flush(){}},LockService:{getScriptLock:()=>lock},ContentService:{MimeType:{JSON:'json'},createTextOutput:text=>({text,setMimeType(){return this;}})}};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync('apps-script/Code.gs','utf8'),ctx);ctx.setup();return {call(data){return JSON.parse(ctx.doPost({postData:{contents:JSON.stringify({token:props.get('ACCESS_TOKEN'),...data})}}).text);},tables,lock};}
const buy={id:'test-buy',type:'buy',date:'2026-01-01T12:00:00Z',qty:2,price:2000,fee:4,feeAsset:'USD',bnbPrice:0,lotId:'',note:'Test'};
test('backend initializes schema and enforces authorization',()=>{const b=backend();assert.equal(b.tables.size,2);assert.equal(b.call({action:'read',token:'wrong'}).ok,false);assert.equal(b.call({action:'read'}).trades.length,0);});
test('backend confirms roundtrip and idempotent retry',()=>{const b=backend();assert.equal(b.call({action:'append',trades:[buy]}).ok,true);assert.equal(b.call({action:'append',trades:[buy]}).trades.length,1);assert.deepEqual(b.call({action:'read'}).trades[0],buy);assert.equal(b.lock.held,false);});
test('server rejects oversell atomically and releases lock',()=>{const b=backend();b.call({action:'append',trades:[buy]});const sell={...buy,id:'test-sale',type:'sell',lotId:buy.id,qty:3,date:'2026-01-02T12:00:00Z'};assert.equal(b.call({action:'append',trades:[sell]}).ok,false);assert.equal(b.call({action:'read'}).trades.length,1);assert.equal(b.lock.held,false);});
test('backend stores partial sale result and refreshes summary',()=>{const b=backend();const sell={...buy,id:'test-sale',type:'sell',lotId:buy.id,qty:1,price:2200,fee:2.2,date:'2026-01-02T12:00:00Z'};assert.equal(b.call({action:'append',trades:[buy,sell]}).ok,true);assert.ok(Math.abs(b.tables.get('ETH_Operacoes').rows[2][10]-195.8)<1e-8);assert.ok(Math.abs(b.tables.get('ETH_Resumo').rows[1][1]-195.8)<1e-8);});
test('formula-like note is escaped and survives retry',()=>{const b=backend(),t={...buy,note:'=IMPORTXML("https://example.com")'};assert.equal(b.call({action:'append',trades:[t]}).ok,true);assert.equal(b.call({action:'append',trades:[t]}).ok,true);});
